### PR TITLE
Fix messageInputBar sendButton not disabled in some situations

### LINKED ISSUE #473: MessageInputBar.sendButton not disabled after clear inputTextView in program
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): 11.x

* Swift Version: 4.0

* Devices/Simulators: iPhone

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?
MessageInputBar.sendButton is still enabled after sending the message. InputTextView's content is cleared in example program:

inputBar.inputTextView.text = String()

## What did you expect to happen?
The sendButton should be disabled.

The notification .UITextViewTextDidChange was not called after clearing inputTextView content programming. Maybe just add 1 one more line to disable the sendButton after clearing.

### PR DESCRIPTION
**Pull request by zhongwuzw**
Fixed #473

### CODE REVIEW

File: Sources/Views/MessageInputBar.swift [hunk 1]
```diff
@@ -703,6 +703,5 @@ open class MessageInputBar: UIView {
     /// Invalidates each of the inputManagers
     open func didSelectSendButton() {
         delegate?.messageInputBar(self, didPressSendButtonWith: inputTextView.text)
-        textViewDidChange()
```
Comment (SD10) [inline Sources/Views/MessageInputBar.swift:706]: 👍

File: Sources/Views/InputTextView.swift [hunk 2]
```diff
@@ -198,6 +200,12 @@ open class InputTextView: UITextView {
         placeholderLabelConstraintSet?.right?.constant = -placeholderLabelInsets.right
     }
     
+    // MARK: - Notification
+    
+    private func postTextViewDidChangeNotification() {
+        NotificationCenter.default.post(name: .UITextViewTextDidChange, object: self)
```
Comment (SD10) [inline Sources/Views/InputTextView.swift:206]: Do you think we need to post a notification here? What about keeping the behavior consistent with UIKit and just disabling the button in the `didSet`? I'm not saying this is the right approach. I want your opinion. cc @nathantannar4 please check this when you get a chance

Comment (zhongwuzw) [reply Sources/Views/InputTextView.swift:206]: Emm, I think it needs. because besides adjust enabled of `sendButton`, we need also handle `placeholderLabel`,`messageInputBar`'s size, and so on.

**Comment by nathantannar4** [comment]
Looks fine

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Review by SD10 — CHANGES_REQUESTED** [review]
@zhongwuzw Care to add a CHANGELOG entry for this under bugfix?
