### PR TITLE
Remove keyboard observers in viewWillDisappear, not deinit

### LINKED ISSUE #1451: Keyboard observers persist after MessagesViewController is dismissed
I'm filing a bug for the same problem that was previously noted by this question: https://github.com/MessageKit/MessageKit/issues/1212

The MessagesViewController removes keyboard observers only in `deinit`, not in `viewWillDisappear`. This is a problem because other parts of the app should be able to use the keyboard without having to trigger things happening in MessageKit.

When `handleKeyboardDidChangeState` is called, it can end up triggering a call to `messageForItem`, but at this point, the dataSource could be cleared, which then causes a crash. I also wonder why `messageForItem` doesn't return an optional? That prevents us from returning nil. 

Here are the relevant pieces:

Inside `MessagesViewController.swift`
```swift
open override func viewDidLayoutSubviews() {
        // Hack to prevent animation of the contentInset after viewDidAppear
        if isFirstLayout {
            defer { isFirstLayout = false }
            addKeyboardObservers()
            messageCollectionViewBottomInset = requiredInitialScrollViewBottomInset()
        }
        adjustScrollViewTopInset()
 }

deinit {
        removeKeyboardObservers()
        removeMenuControllerObservers()
        removeObservers()
        clearMemoryCache()
}
```

and inside `MessagesViewController+Keyboard.swift`
```swift
func addKeyboardObservers() {
        NotificationCenter.default.addObserver(self, selector: #selector(MessagesViewController.handleKeyboardDidChangeState(_:)), name: UIResponder.keyboardWillChangeFrameNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(MessagesViewController.handleTextViewDidBeginEditing(_:)), name: UITextView.textDidBeginEditingNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(MessagesViewController.adjustScrollViewTopInset), name: UIDevice.orientationDidChangeNotification, object: nil)
    }

@objc
    private func handleKeyboardDidChangeState(_ notification: Notification) {
        guard !isMessagesControllerBeingDismissed else { return }

        guard let keyboardStartFrameInScreenCoords = notification.userInfo?[UIResponder.keyboardFrameBeginUserInfoKey] as? CGRect else { return }
        guard !keyboardStartFrameInScreenCoords.isEmpty || UIDevice.current.userInterfaceIdiom != .pad else {
        // [comments] 
            return
        }

        guard self.presentedViewController == nil else {
            // This is important to skip notifications from child modal controllers in iOS >= 13.0
            return
        }
        
        // [very long comment here, justifying this logic below is necessary]

        guard let keyboardEndFrameInScreenCoords = notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? CGRect else { return }
        let keyboardEndFrame = view.convert(keyboardEndFrameInScreenCoords, from: view.window)

        let newBottomInset = requiredScrollViewBottomInset(forKeyboardFrame: keyboardEndFrame)
        let differenceOfBottomInset = newBottomInset - messageCollectionViewBottomInset

        if maintainPositionOnKeyboardFrameChanged && differenceOfBottomInset != 0 {
            let contentOffset = CGPoint(x: messagesCollectionView.contentOffset.x, y: messagesCollectionView.contentOffset.y + differenceOfBottomInset)
            messagesCollectionView.setContentOffset(contentOffset, animated: false)
        }

        messageCollectionViewBottomInset = newBottomInset
    }
```

A function for adjusting the collectionView's bottom inset is _irrelevant_ when the messagesViewController is not visible. Please fix this.

- What version of MessageKit are you using?
Latest version as of this writing (9/2/2020)

- What version of iOS are you running on?
iOS 13.3

- What version of Swift are you running on?
Swift 5

- What device(s) are you testing on? Are these simulators?
No. iPhone 7 and iPhone X

- Is the issue you're experiencing reproducable in the example app?
Yes.

### PR DESCRIPTION
**Pull request by kinoroy**
What does this implement/fix? Explain your changes.
---------------------------------------------------
As suggested by @neugierige , cleans up the keyboard observers when MessagesViewController disappears from the view, instead of waiting for `deinit`. This prevents us from using resources to adjust the bottom offset when the MessagesViewController isn't on screen any longer to display those changes

Does this close any currently open issues?
------------------------------------------
Closes #1451 

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Devices/Simulators:** … iPhone 11 Pro Simulator

**iOS Version:** … iOS 14

**Swift Version:** … 5

**MessageKit Version:** … 3.4.1

### CODE REVIEW

**Review by martinpucik — APPROVED** [review]
LGTM! 🚀

**Comment by neugierige** [comment]
sweet! thank you so much!

File: Sources/Controllers/MessagesViewController.swift [hunk 1]
```diff
@@ -124,6 +124,13 @@ UICollectionViewDelegateFlowLayout, UICollectionViewDataSource, UIGestureRecogni
         addObservers()
     }
     
+    open override func viewWillAppear(_ animated: Bool) {
+        super.viewWillAppear(animated)
+        if !isFirstLayout {
+            addKeyboardObservers()
```
Comment (Kaspik) [inline Sources/Controllers/MessagesViewController.swift:130]: So addObservers doesn't do this?

Comment (kinoroy) [reply Sources/Controllers/MessagesViewController.swift:130]: @Kaspik No, addObservers only adds the observer for didReceiveMemoryWarningNotification, it doesn't call addKeyboardObservers

Comment (Kaspik) [reply Sources/Controllers/MessagesViewController.swift:130]: So `addKeyboardObservers` wasn't called at all? Okay.. I trust you anyways, so feel free to merge it, but probably to development?
