### PR TITLE
Fix message bubble tail orientation invalidation in iOS9

### LINKED ISSUE #468: TailCorner bottomLeft not working in iOS 9
## General Information

* MessageKit Version: 0.13.0

* iOS Version(s): iOS 9.3.5

* Swift Version: 4.0

* Devices/Simulators: iPhone/iPod

* Reproducible in ChatExample? (Yes/No): Yes

##  What happened?

In iOS 9 the ChatExample:
img_0809

## What did you expect to happen?
As in iOS 11, ChatExample:

img_1927

### PR DESCRIPTION
**Pull request by zhongwuzw**
Fixed #468 , #376

### CODE REVIEW

File: Sources/Models/MessageStyle.swift [hunk 1]
```diff
@@ -89,7 +89,7 @@ public enum MessageStyle {
             image = UIImage(cgImage: cgImage, scale: image.scale, orientation: corner.imageOrientation)
         }
 
-        return stretch(image).withRenderingMode(.alwaysTemplate)
```
Comment (SD10) [inline Sources/Models/MessageStyle.swift:92]: I think `.withRenderingMode(.alwaysTemplate)` is necessary, no? We want to ignore the color of the images so that we can apply a different bubble color or border color. The image is black.

Comment (zhongwuzw) [reply Sources/Models/MessageStyle.swift:92]: @SD10 , Nope, we just use the image to mask the `containerView`, so it's just use maskView's alpha channel.

Comment (SD10) [reply Sources/Models/MessageStyle.swift:92]: @zhongwuzw I don't know what I would do without you 😅

**Review by SD10 — APPROVED** [review]

File: Sources/Models/MessageStyle.swift (hunk 1 above)
Comment (zhongwuzw) [reply Sources/Models/MessageStyle.swift:92]: By the way, we should optimize that and not use `mask`, it's performance penalty.

Comment (SD10) [reply Sources/Models/MessageStyle.swift:92]: Yes, I agree. I'm trying to remove the images altogether. See #307 #324. I can't figure out a good API. I will work on this more
