### PR TITLE
Fixed separator line height

### LINKED ISSUE #446: SeparatorLine height
## General Information

* MessageKit Version: 0.12.1

* iOS Version(s): 11

* Swift Version: 4

* Devices/Simulators: both

* Reproducible in ChatExample? (Yes/No): YES

##  What happened?

`messageInputBar.separatorLine.height = 0.5`

## What did you expect to happen?
Not changes height of separator
Maybe i use wrong solution. 

How i can change separatorLine hight in messageInputBar?

### PR DESCRIPTION
**Pull request by zhongwuzw**
Closes #578 , fixed #446 .

### CODE REVIEW

File: Sources/Views/MessageInputBar.swift [hunk 1]
```diff
@@ -340,7 +340,7 @@ open class MessageInputBar: UIView {
     private func setupConstraints() {
         
         // The constraints within the MessageInputBar
-        separatorLine.addConstraints(topAnchor, left: leftAnchor, right: rightAnchor, heightConstant: 1)
+        separatorLine.addConstraints(topAnchor, left: leftAnchor, right: rightAnchor)
```
Comment (SD10) [inline Sources/Views/MessageInputBar.swift:343]: Does this change the default appearance?

Comment (zhongwuzw) [reply Sources/Views/MessageInputBar.swift:343]: Nope.

**Review by SD10 — APPROVED** [review]
👌 :shipit:
