### PR TITLE
Fix font invalid for attributedString

### LINKED ISSUE #557: New attributedText message does not display correct until scroll from visible->invisible->visible
I modified the demo code like this:
____________________

```swift
extension ConversationViewController: MessageInputBarDelegate {

    func messageInputBar(_ inputBar: MessageInputBar, didPressSendButtonWith text: String) {
        
        // Each NSTextAttachment that contains an image will count as one empty character in the text: String
        
        for component in inputBar.inputTextView.components {
            
            if let image = component as? UIImage {
                
                let imageMessage = MockMessage(image: image, sender: currentSender(), messageId: UUID().uuidString, date: Date())
                messageList.append(imageMessage)
                messagesCollectionView.insertSections([messageList.count - 1])
                
            } else if let text = component as? String {
                
                let attributedText = NSAttributedString(string: text, attributes: [.font: UIFont.systemFont(ofSize: 15), .foregroundColor: UIColor.blue])
                
                let msg9String = "Use .attributedText() to add bold, italic, colored text and more..."
                let msg9Text = NSString(string: msg9String)
                let msg9AttributedText = NSMutableAttributedString(string: String(msg9Text))
                
                msg9AttributedText.addAttribute(NSAttributedStringKey.font, value: UIFont.preferredFont(forTextStyle: .body), range: NSRange(location: 0, length: msg9Text.length))
                msg9AttributedText.addAttributes([NSAttributedStringKey.font: UIFont.monospacedDigitSystemFont(ofSize: UIFont.systemFontSize, weight: UIFont.Weight.bold)], range: msg9Text.range(of: ".attributedText()"))
                msg9AttributedText.addAttributes([NSAttributedStringKey.font: UIFont.boldSystemFont(ofSize: UIFont.systemFontSize)], range: msg9Text.range(of: "bold"))
                msg9AttributedText.addAttributes([NSAttributedStringKey.font: UIFont.italicSystemFont(ofSize: UIFont.systemFontSize)], range: msg9Text.range(of: "italic"))
                msg9AttributedText.addAttributes([NSAttributedStringKey.foregroundColor: UIColor.red], range: msg9Text.range(of: "colored"))
                
                
                let message = MockMessage(attributedText: msg9AttributedText, sender: currentSender(), messageId: UUID().uuidString, date: Date())
                messageList.append(message)
                messagesCollectionView.insertSections([messageList.count - 1])
            }
            
        }
        
        inputBar.inputTextView.text = String()
        messagesCollectionView.scrollToBottom()
    }

}
```
____________________

So whatever I send, it will send a new attributedText message.
You can see the new attributedText message will not display correct.

But after you scroll the colletionview up and down, it may display correct.

### PR DESCRIPTION
**Pull request by zhongwuzw**
* Fixed #557 . 
* Added `Xcode 9.3` related config file.

- [x] Added CHANGELOG.

Another issue still exist, like `textColor`, it would leads to invalidation of `attributedString`'s `color` attributes.

We need to investigate that wether remove `textColor(for message: MessageType, at indexPath: IndexPath, in messagesCollectionView: MessagesCollectionView) -> UIColor`, it also leads to invalidation of `attributedString`'s `color` attributes.

### CODE REVIEW

**Comment by SD10** [comment]
@zhongwuzw I have to wrap my head around this one. I think the bug is caused [by this](https://github.com/MessageKit/MessageKit/blob/c476abe5050bc7c3d4f86edc157d8c63be9de9f4/Sources/Layout/MessagesCollectionViewFlowLayout.swift#L284)?

**Comment by SD10** [comment]
@zhongwuzw In Slack we were discussing changing `textColor(for:at:in)` so that it is not used on `.attributedText` case but only `.text` case.

**Comment by zhongwuzw** [comment]
> I think the bug is caused by this?

Nope, this is only apply when `attributedString` not set `font` attribute, otherwise, maybe we can remove this disposition.

> In Slack we were discussing changing textColor(for:at:in) so that it is not used on .attributedText case but only .text case.

👍 , it needs.

File: Sources/Views/Cells/TextMessageCell.swift [hunk 1]
```diff
@@ -79,6 +79,7 @@ open class TextMessageCell: MessageCollectionViewCell {
             switch message.data {
             case .text(let text), .emoji(let text):
                 messageLabel.text = text
+                messageLabel.applyMessageLableFont()
```
Comment (SD10) [inline Sources/Views/Cells/TextMessageCell.swift]: Can't we just apply the `UIFont` inside of here without this method? I don't mind repeating code. This way of doing it makes it very confusing to me.

**Review by SD10 — APPROVED** [review]
@zhongwuzw Thanks for fixing this. It's a pretty bad bug. After CI passes I will merge and do a release

**Comment by zhongwuzw** [comment]
@SD10 , 👌 , I'll commit a fix to `move-open` branch either.
